// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRFPwx55hEj06_NMQwtTMF54nEcDPvfTM',
    appId: '1:848704699189:web:24932cfde2732a64186a7c',
    messagingSenderId: '848704699189',
    projectId: 'dashboard-8e414',
    authDomain: 'dashboard-8e414.firebaseapp.com',
    databaseURL: 'https://dashboard-8e414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dashboard-8e414.appspot.com',
    measurementId: 'G-3J7TJ8K58B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOlNCFDKDlaUt8qghdz0kIBf6d2YK5BWw',
    appId: '1:848704699189:android:3068be3371c81ab7186a7c',
    messagingSenderId: '848704699189',
    projectId: 'dashboard-8e414',
    databaseURL: 'https://dashboard-8e414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dashboard-8e414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YYuXq51iCRzgY4djGeE6uM3bFPZit7E',
    appId: '1:848704699189:ios:7908af75e9cf5909186a7c',
    messagingSenderId: '848704699189',
    projectId: 'dashboard-8e414',
    databaseURL: 'https://dashboard-8e414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dashboard-8e414.appspot.com',
    iosClientId: '848704699189-31en250di97bvu2f009hsjicd3rkuc4v.apps.googleusercontent.com',
    iosBundleId: 'com.bamba.mpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YYuXq51iCRzgY4djGeE6uM3bFPZit7E',
    appId: '1:848704699189:ios:d7a104ab5d1ef582186a7c',
    messagingSenderId: '848704699189',
    projectId: 'dashboard-8e414',
    databaseURL: 'https://dashboard-8e414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dashboard-8e414.appspot.com',
    iosClientId: '848704699189-p496l8gqsdv3a322g373kq9lou03l355.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRFPwx55hEj06_NMQwtTMF54nEcDPvfTM',
    appId: '1:848704699189:web:ce6560bbd1e0d562186a7c',
    messagingSenderId: '848704699189',
    projectId: 'dashboard-8e414',
    authDomain: 'dashboard-8e414.firebaseapp.com',
    databaseURL: 'https://dashboard-8e414-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dashboard-8e414.appspot.com',
    measurementId: 'G-CHDF717C0C',
  );
}
